[supervisord]
nodaemon=true
user=root
logfile=/dev/null
pidfile=/tmp/supervisord.pid

[program:worker-djen]
command=php /usr/local/bin/queue-worker.php
environment=TOGARE_QUEUE_NAME="djen",TOGARE_DB_HOST="%(ENV_TOGARE_DB_HOST)s",TOGARE_DB_NAME="%(ENV_TOGARE_DB_NAME)s",TOGARE_DB_USER="%(ENV_TOGARE_DB_USER)s",TOGARE_DB_PASSWORD="%(ENV_TOGARE_DB_PASSWORD)s"
autostart=true
autorestart=true
startretries=5
stopwaitsecs=60
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:worker-internal]
command=php /usr/local/bin/queue-worker.php
environment=TOGARE_QUEUE_NAME="internal",TOGARE_DB_HOST="%(ENV_TOGARE_DB_HOST)s",TOGARE_DB_NAME="%(ENV_TOGARE_DB_NAME)s",TOGARE_DB_USER="%(ENV_TOGARE_DB_USER)s",TOGARE_DB_PASSWORD="%(ENV_TOGARE_DB_PASSWORD)s"
autostart=true
autorestart=true
startretries=5
stopwaitsecs=60
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
